language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get update -qq
  - sudo apt-get install -y python-setuptools python-qt4 python-qt4-gl git-core python-qt4-phonon build-essential python-dev subversion python-pygame
  # Install SWIG >= 3 for box2d-py (See #83).
  - sudo apt-get -y install -t trusty-backports swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - sudo easy_install -U box2d
  - "sh -e /etc/init.d/xvfb start"
script:
  - python -m unittest discover pilasengine/tests '*.py'
virtualenv:
  system_site_packages: true
